timetracking/config/routes.rb
Rails.application.routes.draw do
  get '/' => 'site#home'
  get '/contact' => 'site#contact'

  resources :people
  resources :projects do
  	resources :entries
  end
  
  # get '/contact' => 'site#contact'
  # get '/projects' => 'projects#index'
  # get '/projects/:id' => 'projects#show'
  # get '/projects/:project_id/entries' => 'entries#index', as: 'project_entries'
  # post '/projects/:project_id/entries' => 'entries#create'
  # get '/projects/:project_id/entries/new' => 'entries#new'
end

timetracking/app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :project
	validates :hours, presence: true
	validates :minutes, presence: true
	validates :date, presence: true
end

timetracking/app/models/participation.rb
class Participation < ActiveRecord::Base
	belongs_to :person
	belongs_to :project
end

timetracking/app/models/person.rb
class Person < ActiveRecord::Base
	has_many :participations
	has_many :projects, through: :participations

	def self.show_people
		order("created_at DESC")
	end
end

timetracking/app/models/project.rb
class Project < ActiveRecord::Base
	has_many :entries
	has_many :participations
	has_many :people, through: :participations

	has_attached_file :logo, styles: {:medium => '300x300>', :thumb => '100x100>'}
	validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\Z/

	validates :name, presence: true, uniqueness: true, length: { maximum: 30 }
	validates :description, presence: true, length: { maximum: 50 }



	def self.iron_find id 
		where("id = ?",id)
	end
	def self.clean_old
		where("created_at < ?", Time.now.midnight - 7.days).destroy_all
	end
	def self.last_created_projects number
		order("created_at DESC").limit(number)
	end

	def total_hours_in_month
		from = Date.new(Date.today.year,Date.today.month,1)
		to = Date.new(Date.today.year,Date.today.month, -1)
		total = 0
		minutes = 0
		entries.where(date: from..to).each do |entry|
			total += entry.hours
			minutes += entry.minutes
		end
		total += minutes / 60
		total.to_s + " h " + (minutes % 60).to_s + " min"
	end
end

timetracking/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

timetracking/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	def index
		@project = Project.find params[:project_id]
		@entries = @project.entries
	end
	def new
		@project = Project.find params[:project_id]
		@entry = @project.entries.new
	end
	def create
		@project = Project.find params[:project_id]
		@entry = @project.entries.new entry_params
		if @entry.save
			redirect_to action: 'index', controller: 'entries', project_id: @project.id
		else
			render 'new'
		end
	end

	def edit
		@project = Project.find params[:project_id]
		@entry = @project.entries.find(params[:id])
	end

	def update
		@project = Project.find params[:project_id]
		@entry = @project.entries.find(params[:id])
		if @entry.update_attributes entry_params
			redirect_to action: 'index', controller: 'entries', project_id: @project.id
		else
			render 'edit'
		end
	end	

	def destroy
		@project = Project.find(params[:project_id])
		@project.entries.find(params[:id]).destroy
		redirect_to action: 'index', controller: 'entries', project_id: @project.id
	end

	private

	def entry_params
		params.require(:entry).permit(:hours, :minutes, :date, :comments)
	end
end

timetracking/app/controllers/people_controller.rb
class PeopleController < ApplicationController
	def index
		@people = Person.show_people
		if @people.empty?
			render 'no_people_found'
		end
	end

	def show
		begin
			@person = Person.find params[:id]
		rescue ActiveRecord::RecordNotFound
			render 'no_people_found'
		end
	end
	def new
		@person = Person.new
	end
	def create
		@person = Person.new person_params
		if @person.save
			@person.projects << Project.find(params[:participation][:project_id])
			redirect_to action: 'index', controller: 'people'
		else
			render 'new'
		end
	end

	def edit
		@person = Person.find params[:id]
	end

	def update
		@person = Person.find params[:id]
		if @person.update_attributes person_params
			redirect_to action: 'index', controller: 'people'
		else
			render 'edit'
		end
		begin
		 	@person.projects << Project.find(params[:participation][:project_id])
		rescue ActiveRecord::RecordNotUnique
		end
	end

	def destroy
		@person = Person.find(params[:id])
		@person.destroy
		redirect_to action: 'index', controller: 'people'
	end

	private

	def person_params
		params.require(:person).permit(:name)
	end
end

timetracking/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@list = Project.last_created_projects(10)
		if @list.empty?
			render 'no_projects', layout: 'no_projects'
		end
	end
	def show
		begin
			@project = Project.find params[:id]
			@worked = @project.total_hours_in_month
		rescue ActiveRecord::RecordNotFound
			render 'no_projects_found'
		end
	end
	def new
		@project = Project.new
	end
	def create
		@project = Project.new project_params
		if @project.save
			redirect_to action: 'index', controller: 'projects'
		else
			render 'new'
		end
	end

	def edit
		@project = Project.find params[:id]
	end

	def update
		@project = Project.find params[:id]
		if @project.update_attributes project_params
			redirect_to action: 'index', controller: 'projects'
		else
			render 'edit'
		end
	end

	def destroy
		@project = Project.find(params[:id])
		@project.entries.destroy_all
		@project.destroy
		redirect_to action: 'index', controller: 'projects'
	end

	private

	def project_params
		params.require(:project).permit(:name, :description, :logo)
	end
end

timetracking/app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home
	end
	def contact
	end
end

timetracking/app/helpers/application_helper.rb
module ApplicationHelper
end

timetracking/app/helpers/entries_helper.rb
module EntriesHelper
end

timetracking/app/helpers/people_helper.rb
module PeopleHelper
end

timetracking/app/helpers/projects_helper.rb
module ProjectsHelper
end

timetracking/app/helpers/site_helper.rb
module SiteHelper
end

timetracking/app/views/entries/_form.erb
<% if @entry.errors.any? %>
	<ul>
		<% @entry.errors.full_messages.each do |error_msg| %>
			<li><%= error_msg %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for [@project, @entry] do |f| %>
	<%= f.label :hours %>
	<%= f.text_field :hours %>
	<br>
	<%= f.label :minutes %>
	<%= f.text_field :minutes %>
	<br>
	<%= f.label :date %>
	<%= f.date_field :date %>
	<br>
	<%= f.label :comments %>
	<%= f.text_field :comments %>
	<br>
	<%= f.submit "Save" %>
<% end %>
<%= link_to('Cancel', project_entries_path) %>

timetracking/app/views/entries/edit.erb
<h1>Edit entry</h1>

<%= render 'form' %>

timetracking/app/views/entries/index.erb
<h2><% @project.name %></h2>
<ul>
	<% @entries.each do |entry| %>
		<li>
			<%= entry.hours %> h 
			<%= entry.minutes %> m -
			<%= entry.date.strftime('%D') %> 
			<%= link_to('Edit entry', edit_project_entry_path(@project.id, entry.id)) %>
			<%= link_to('Delete', project_entry_path(@project.id, entry.id), method: :delete, data: { confirm: 'Are you sure?' } ) %>
		</li>
	<% end %>
</ul>
<%= link_to('New entry', new_project_entry_path(@project.id)) %>

timetracking/app/views/entries/new.erb
<h1>New entry</h1>

<% if @entry.errors.any? %>
	<ul>
		<% @entry.errors.full_messages.each do |error_msg| %>
			<li><%= error_msg %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for [@project, @entry] do |f| %>
	<%= f.label :hours %>
	<%= f.text_field :hours %>
	<br>
	<%= f.label :minutes %>
	<%= f.text_field :minutes %>
	<br>
	<%= f.label :date %>
	<%= f.date_field :date %>
	<br>
	<%= f.label :comments %>
	<%= f.text_field :comments %>
	<br>
	<%= f.submit "Save" %>
<% end %>
<%= link_to('Cancel', project_entries_path) %>

timetracking/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

timetracking/app/views/layouts/no_projects.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header style="background: yellow">
		<h1>Sorry</h1>		
	</header>

	<%= yield %>

</body>
</html>

timetracking/app/views/people/_form.erb
<% if @person.errors.any? %>
	<ul>
		<% @person.errors.full_messages.each do |error_msg| %>
			<li><%= error_msg %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for @person do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	Add participation on Project
	<%= select("participation", "project_id", Project.all.collect {|p| [ p.name, p.id ] }, {include_blank: 'None'}) %>
	<br>
	<%= f.submit "Save" %>
<% end %>

timetracking/app/views/people/edit.erb
<h1>Edit Person</h1>

<%= render 'form' %>

timetracking/app/views/people/index.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Project</title>
</head>
<body>
	<% if @people %>
		<ul>
			<% @people.each do |person| %>
				<li>
					<%= link_to(person.name, person_path(person.id)) %>
				
					<%= link_to('Edit profile', edit_person_path(person.id)) %>
					<%= link_to('Delete person', person_path(person.id), method: :delete, data: { confirm: 'Are you sure?'}) %>
				</li>
			<% end %>
		</ul>
	<% end %>
	<%= link_to('Create new', new_person_path) %>
</body>
</html>

timetracking/app/views/people/new.erb
<h1>Form to create a new person</h1>

<%= render 'form' %>

timetracking/app/views/people/no_people_found.erb
<h1>People not found</h1>

timetracking/app/views/people/show.erb
<%= @person.name %>
<br>
<h2>Projects</h2>
<ul>
	<% @person.projects.each do |project| %>
		<li><%= project.name %></li>
	<% end %>
</ul>
<br>
<%= link_to('People index', people_path) %>

timetracking/app/views/projects/_form.erb
<% if @project.errors.any? %>
	<ul>
		<% @project.errors.full_messages.each do |error_msg| %>
			<li><%= error_msg %></li>
		<% end %>
	</ul>
<% end %>

<%= form_for @project, :html => {:multipart => true} do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<br>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<br>
	<%= f.label :logo %>
	<%= f.file_field :logo %>
	<br>
	<%= f.submit "Save" %>
<% end %>

timetracking/app/views/projects/edit.erb
<h1>Edit project</h1>

<%= render 'form' %>

timetracking/app/views/projects/index.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Project</title>
</head>
<body>
	<% if @list %>
		<ul>
			<% @list.each do |project| %>
				<li>
					<%= image_tag project.logo.url(:thumb) %>
					<%= link_to(project.name, project_entries_path(project)) %>
					<% if  !project.description.empty? %>
						- <%= project.description %> 
					<% end %>
					<%= link_to('Edit Project', edit_project_path(project.id)) %>
					<%= link_to('Delete Project', project_path(project.id), method: :delete, data: { confirm: 'Are you sure?'}) %>
				</li>
			<% end %>
		</ul>
	<% end %>
	<%= link_to('Create new', new_project_path) %>
</body>
</html>

timetracking/app/views/projects/new.erb
<h1>Form to add new project</h1>

<%= render 'form' %>

timetracking/app/views/projects/no_projects.erb
<h1>There are not projects to show</h1>

timetracking/app/views/projects/no_projects_found.erb
<h1>Project not found</h1>

timetracking/app/views/projects/show.erb
	<%= @project.name %>
	<% if  !@project.description.empty? %>
		- <%= @project.description %> 
	<% end %>
	<%= image_tag @project.logo.url %> 

	<h2>Total hours worked at this project in this month: <%= @worked %></h2>

	<%= link_to('View entries', project_entries_path(@project.id)) %>

timetracking/app/views/site/contact.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>contact</title>
</head>
<body>
	<h1>What's up? This is the contact page</h1>
</body>
</html>

timetracking/app/views/site/home.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>View home</title>
</head>
<body>
	<h1>First view on ruby on rails</h1>
</body>
</html>